# Run with: cmake -P if-else.cmake
set(VAR1 TRUE)
if(VAR1)
    message("VAR1 is true")
    message(STATUS "VAR1 is: ${VAR1}")
else()
    message("VAR1 is false")
endif()

message("----------------")

set(VAR2 1)
if(VAR2)
    message("VAR2 is true")
    message(STATUS "VAR2 is: ${VAR2}")
else()
    message("VAR2 is false")
endif()

if(${VAR2})
    message("VAR2 is true")
    message(STATUS "VAR2 is: ${VAR2}")
else()
    message("VAR2 is false")
endif()

message("----------------")

if(VAR3)
    message("VAR3 is defined")
    message(STATUS "VAR3 is: ${VAR3}")
else()
    message("VAR3 is not defined")
endif()

if(DEFINED VAR3)  # Check if VAR3 is defined
    message("VAR3 is defined")
    message(STATUS "VAR3 is: ${VAR3}")
else()
    message("VAR3 is not defined")
endif()

message("----------------")
set(VAR4 off)
set(VAR5 "VAR4")
if(${VAR5})
    message("VAR5 is true")
    message(STATUS "VAR5 is: ${VAR5}")
else()
    message("VAR5 is false")
    message(STATUS "VAR5 is: ${VAR5}")
endif()

if(VAR5)
    message("VAR5 is true")
    message(STATUS "VAR5 is: ${VAR5}")
else()
    message("VAR5 is false")
endif()

message("----------------")
if(1 EQUAL 1)
    message("1 is equal to 1")
else()
    message("1 is not equal to 1")
endif()

if(1 EQUAL 2)
    message("1 is equal to 2")
else()
    message("1 is not equal to 2")
endif()

set(NUM1 1)
set(NUM2 2)
if(${NUM1} LESS ${NUM2})
    message("${NUM1} is less than ${NUM2}")
else()
    message("${NUM1} is not less than ${NUM2}")
endif()

if(${NUM1} GREATER ${NUM2})
    message("${NUM1} is greater than ${NUM2}")
else()
    message("${NUM1} is not greater than ${NUM2}")
endif()

if(NUM1 LESS NUM2)
    message("NUM1 is less than NUM2")
else()
    message("NUM1 is not less than NUM2")
endif()

set(DOG 12)
set(PIG 13)

if(DOG STRLESS_EQUAL PIG)
    message("DOG is less than or equal to PIG")
else()
    message("DOG is not less than or equal to PIG")
endif()

if(DOG STREQUAL PIG)
    message("DOG is equal to PIG")
else()
    message("DOG is not equal to PIG")
endif()

if("123" STRLESS_EQUAL "45")
    message("123 is less than or equal to 45")
else()
    message("123 is not less than or equal to 45")
endif()

if("apple" STRLESS_EQUAL "apples")
    message("apple is less than or equal to apples")
else()
    message("apple is not less than or equal to apples")
endif()

if("apple" STRLESS_EQUAL "Apple")
    message("apple is less than or equal to Apple")
else()
    message("apple is not less than or equal to Apple")
endif()
